import React, { useMemo } from 'react'

import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

// import Dot from "../src/components/Dot";
import Header from "../src/components/Header";
// import FinesList from "../src/containers/FinesList";
//
import styles from "../styles/Home.module.css";

export default function Home() {
  // const columns = useMemo(() =>  [
  //   {
  //     Header: 'Players', accessor: 'player'
  //   },
  //   {
  //     Header: 'Game 1', accessor: 'game1'
  //   },
  //   {
  //     Header: 'Game 2', accessor: 'game2'
  //   },
  //   {
  //     Header: 'Game 3', accessor: 'game3'
  //   },
  //   {
  //     Header: 'Total', accessor: 'total'
  //   }
  // ], [])
  //
  //
  // const data = useMemo(() => new Array(4).fill({
  //   player: 'Harry Wright',
  //   game1: ['H', 'D', 'H', 'D', 'H', 'R', 'H', 'D', 'H', 'D', 'H', 'R'].join(' '),
  //   game2: ['H', 'D', 'H'].join(' '),
  //   game3: ['H', 'D', 'H'].join(' '),
  //   total: '£2.50'
  // }), [])

  return (
    <>
      <Head>
        <title>Powerplay 4&apos;s | Week 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container-lg" style={{ padding: '32px' }}>
        <div className='meta' style={{ paddingBottom: '16px' }}>
          <Header as={'h1'} title={'Powerplay 4\'s Week 1'} />
          <div className='meta_footer'>
            <span>{new Date().toUTCString()}</span>
            <span style={{ paddingLeft: '8px' }}>
              {/*<Dot size={'10px'} color={'green'} />*/}
            </span>
          </div>
        </div>
        <hr />
        {/*<FinesList columns={columns} data={data} title='Players' />*/}
        {/*<FinesList columns={columns} data={data.slice(0, 1)} title='Captains' />*/}
      </div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  )
}
